### ISSUE TITLE
openStream() is sync but can’t be

### ISSUE THREAD

**Issue by addaleax** [nodejs/quic#181]
Calling `openStream()` immediately after `client.connect()` crashes because the underlying session handle isn’t set yet, but it requires the handle for synchronous operation.

I’m not sure how to best approach this from an API perspective. There isn’t really any way we can fully make the current API work, I think, because at least the stream IDs are something we don’t really know before the underlying `QuicSession` is set up.

Maybe this should just throw an exception in that case?

**Comment by jasnell** [comment]
So this one is going to be a bit complicated. It should be absolutely possible to call `openStream()` immediately after `client.connect()` with the `QuicStream` remaining in a pending state until the underlying `QuicSession` handle has been set. While in the pending state, it should be possible to set headers (when relevant) and even begin queuing data to send (with the Duplex operating in corked mode). If the `QuicSession` is a client, then any pending `QuicStream` instances should actually become 0RTT streams, with initial request headers being transmitted as part of the 0RTT initial handshake. None of this piece is implemented yet tho because I just wasn't sure how we were going to do so. A `QuicStream` would remain in the pending state until the `QuicSession` is established and is in a state where it can uncork the Duplex and begin flowing data.

Note, ngtcp2 will allow streams to be opened during the handshake, and will assign id's to those, with the assumption that those are being used as 0RTT streams.

**Comment by jasnell** [comment]
The flow on this then... 

* Any time after the creation of a JavaScript `QuicClientSession` or `QuicServerSession`, a JavaScript `QuicStream` may be created.

* If, at the time the `QuicStream` is created, the parent `QuicSession` does not have a handle set, the `QuicStream` exists in a `Pending` state, state changing operations in JavaScript are queued. Note that this should never actually happen with `QuicServerSession` instances which always have the handle created first, so the rest assumes `QuicClientSession` only...

* If, at the time the `QuicClientSession` has it's handle set, the TLS handshake is still initiating, any existing pending `QuicStream` instances would be created and moved immediately to a `ORTT` state, which allows some initial data to be transmitted within very strict limits set by the QUIC spec.

* Once the TLS handshake completes, any existing `QuicStream` instances would move to a `Ready` state.

This model allows the `QuicStream` to be created synchronously but requires a bit more complicated state tracking at the native layer than what is currently implemented.

**Comment by addaleax** [comment]
Having slept about this … what if we always create the QUIC handles immediately, but queue outgoing UDP data (and `QuicSession::SendPendingData()` calls) until the UDP socket is ready/bound? Would that maybe make more sense than delaying the creation of C++ handles?

**Comment by jasnell** [comment]
We can create the C++ handles immediately but queuing at the UDP level is not really possible as ngtcp2 requires various state changes in order to be able to even generate the UDP packets. For `QuicStream`, queuing at the javascript layer similar to what we do in http/2 makes the most sense until the `QuicSession` is in a state where the `QuicSession` can process the stream data.
